/**
 * Known per-chain protocol addresses (from `docs/ROBINHOOD_CHAIN.md`, stored EIP-55 checksummed)
 * and the deployed launchpad lookup (`docs/SPEC.md` §3.1).
 *
 * No file-system or environment access: deployments come from `deployments.generated.ts`
 * (generated by `node scripts/sync-deployments.mjs` from `contracts/deployments/*.json`). Env
 * overrides (`LAUNCHPAD_ADDRESS`, `VITE_LAUNCHPAD_ADDRESS`; the zero address counts as unset) are
 * applied by the consumer.
 *
 * @module addresses
 */
import type { Address } from 'viem';
import { ANVIL_CHAIN_ID, ROBINHOOD_CHAIN_ID, ROBINHOOD_TESTNET_CHAIN_ID } from './chains.js';
import { DEPLOYMENTS } from './deployments.generated.js';

/** Protocol addresses known for a chain. */
export interface ChainAddresses {
  weth9?: Address;
  uniswapV3Factory?: Address;
  uniswapV3PositionManager?: Address;
  uniswapV3SwapRouter02?: Address;
  uniswapV3QuoterV2?: Address;
  uniswapV3TickLens?: Address;
  uniswapV3PoolInitCodeHash?: `0x${string}`;
  uniswapV2Factory?: Address;
  uniswapV2Router02?: Address;
  uniswapV4PoolManager?: Address;
  uniswapV4PositionManager?: Address;
  universalRouter?: Address;
  permit2?: Address;
  /** Uniswap v3 fee tier used by `UniswapV3Graduator` (10000 = 1 %). */
  uniswapV3FeeTier: number;
}

/** Default Uniswap v3 fee tier for graduation pools (1 %). */
export const DEFAULT_UNIV3_FEE_TIER = 10_000;

/** Robinhood Chain mainnet (4663) protocol addresses. */
export const ROBINHOOD_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  weth9: '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  uniswapV3Factory: '0x1f7d7550B1b028f7571E69A784071F0205FD2EfA',
  uniswapV3PositionManager: '0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3',
  uniswapV3SwapRouter02: '0xCaf681a66D020601342297493863E78C959E5cb2',
  uniswapV3QuoterV2: '0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7',
  uniswapV3TickLens: '0x7DfD4F31be6814D2906BDE155c3e1B146EAc1468',
  uniswapV3PoolInitCodeHash: '0xe34f199b19b2b4f47f68442619d555527d244f78a3297ea89325f843f87b8b54',
  uniswapV2Factory: '0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f',
  uniswapV2Router02: '0x89e5DB8B5aA49aA85AC63f691524311AEB649eba',
  uniswapV4PoolManager: '0x8366a39CC670B4001A1121B8F6A443A643e40951',
  uniswapV4PositionManager: '0x58daec3116aae6D93017bAAea7749052E8a04fA7',
  universalRouter: '0x204FAca1764B154221e35c0d20aBb3c525710498',
  permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Robinhood Chain testnet (46630). No public Uniswap v3 deployment is known: use `MockGraduator`. */
export const ROBINHOOD_TESTNET_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  weth9: '0x7943e237c7F95DA44E0301572D358911207852Fa',
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Local anvil: nothing pre-deployed. */
export const ANVIL_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Known addresses keyed by chain id. */
export const ADDRESSES: Readonly<Record<number, Readonly<ChainAddresses>>> = Object.freeze({
  [ROBINHOOD_CHAIN_ID]: ROBINHOOD_ADDRESSES,
  [ROBINHOOD_TESTNET_CHAIN_ID]: ROBINHOOD_TESTNET_ADDRESSES,
  [ANVIL_CHAIN_ID]: ANVIL_ADDRESSES,
});

/** Returns the known addresses for `chainId`, or `undefined`. */
export function addressesFor(chainId: number): Readonly<ChainAddresses> | undefined {
  return ADDRESSES[chainId];
}

/** One deployment, as written by `script/Deploy.s.sol` to `contracts/deployments/<chainId>.json`. */
export interface DeploymentRecord {
  chainId: number;
  launchpad: Address;
  graduator: Address;
  graduatorKind: 'uniswapv3' | 'mock';
  /** Unix seconds (`block.timestamp` of the deployment). */
  deployedAt: number;
}

export { DEPLOYMENTS };

const ZERO = '0x0000000000000000000000000000000000000000';

/**
 * The deployed `MindLaunchpad` for `chainId` from {@link DEPLOYMENTS}, or `undefined` (also when
 * the recorded address is the zero address).
 */
export function launchpadAddress(chainId: number): Address | undefined {
  const launchpad = DEPLOYMENTS[chainId]?.launchpad;
  return launchpad === undefined || launchpad.toLowerCase() === ZERO ? undefined : launchpad;
}
