/**
 * Known per-chain protocol addresses (from `docs/ROBINHOOD_CHAIN.md`, stored EIP-55 checksummed),
 * the Pons V2 contracts on Robinhood Chain mainnet (`docs/SPEC.md` §9.1) and the deployed
 * launchpad / registry lookup (§3.1, §9.3).
 *
 * No file-system or environment access: deployments come from `deployments.generated.ts`
 * (generated by `node scripts/sync-deployments.mjs` from `contracts/deployments/*.json`). Env
 * overrides (`LAUNCHPAD_ADDRESS` / `REGISTRY_ADDRESS` / `PONS_*`, `VITE_LAUNCHPAD_ADDRESS` /
 * `VITE_REGISTRY_ADDRESS`; the zero address counts as unset) are applied by the consumer.
 *
 * @module addresses
 */
import type { Address } from 'viem';
import { ANVIL_CHAIN_ID, ROBINHOOD_CHAIN_ID, ROBINHOOD_TESTNET_CHAIN_ID } from './chains.js';
import { DEPLOYMENTS } from './deployments.generated.js';

/** Protocol addresses known for a chain. */
export interface ChainAddresses {
  weth9?: Address;
  uniswapV3Factory?: Address;
  uniswapV3PositionManager?: Address;
  uniswapV3SwapRouter02?: Address;
  uniswapV3QuoterV2?: Address;
  uniswapV3TickLens?: Address;
  uniswapV3PoolInitCodeHash?: `0x${string}`;
  uniswapV2Factory?: Address;
  uniswapV2Router02?: Address;
  uniswapV4PoolManager?: Address;
  uniswapV4PositionManager?: Address;
  universalRouter?: Address;
  permit2?: Address;
  /** Uniswap v3 fee tier used by `UniswapV3Graduator` (10000 = 1 %). */
  uniswapV3FeeTier: number;
}

/** Default Uniswap v3 fee tier for graduation pools (1 %). */
export const DEFAULT_UNIV3_FEE_TIER = 10_000;

/** Robinhood Chain mainnet (4663) protocol addresses. */
export const ROBINHOOD_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  weth9: '0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',
  uniswapV3Factory: '0x1f7d7550B1b028f7571E69A784071F0205FD2EfA',
  uniswapV3PositionManager: '0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3',
  uniswapV3SwapRouter02: '0xCaf681a66D020601342297493863E78C959E5cb2',
  uniswapV3QuoterV2: '0x33e885eD0Ec9bF04EcfB19341582aADCb4c8A9E7',
  uniswapV3TickLens: '0x7DfD4F31be6814D2906BDE155c3e1B146EAc1468',
  uniswapV3PoolInitCodeHash: '0xe34f199b19b2b4f47f68442619d555527d244f78a3297ea89325f843f87b8b54',
  uniswapV2Factory: '0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f',
  uniswapV2Router02: '0x89e5DB8B5aA49aA85AC63f691524311AEB649eba',
  uniswapV4PoolManager: '0x8366a39CC670B4001A1121B8F6A443A643e40951',
  uniswapV4PositionManager: '0x58daec3116aae6D93017bAAea7749052E8a04fA7',
  universalRouter: '0x204FAca1764B154221e35c0d20aBb3c525710498',
  permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Robinhood Chain testnet (46630). No public Uniswap v3 deployment is known: use `MockGraduator`. */
export const ROBINHOOD_TESTNET_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  weth9: '0x7943e237c7F95DA44E0301572D358911207852Fa',
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Local anvil: nothing pre-deployed. */
export const ANVIL_ADDRESSES: Readonly<ChainAddresses> = Object.freeze({
  uniswapV3FeeTier: DEFAULT_UNIV3_FEE_TIER,
} satisfies ChainAddresses);

/** Known addresses keyed by chain id. */
export const ADDRESSES: Readonly<Record<number, Readonly<ChainAddresses>>> = Object.freeze({
  [ROBINHOOD_CHAIN_ID]: ROBINHOOD_ADDRESSES,
  [ROBINHOOD_TESTNET_CHAIN_ID]: ROBINHOOD_TESTNET_ADDRESSES,
  [ANVIL_CHAIN_ID]: ANVIL_ADDRESSES,
});

/** Returns the known addresses for `chainId`, or `undefined`. */
export function addressesFor(chainId: number): Readonly<ChainAddresses> | undefined {
  return ADDRESSES[chainId];
}

/**
 * Pons V2 contracts (`docs/SPEC.md` §9.1). Pons is a third-party launchpad: these contracts are
 * outside the www-rh audit scope.
 */
export interface PonsAddresses {
  /** `PonsV2LaunchFactory` */
  factory: Address;
  /** `PonsV2LaunchAndBuy` (router; not used by the registry) */
  router: Address;
  /** `FeeEscrow` (`IPonsV2FeeEscrow`): creator fees are credited here on sweeps */
  feeEscrow: Address;
  /** `PonsV2MemeHook`: fee policy + post-graduation pool fees */
  memeHook: Address;
  /** `PonsV2LaunchLocker` (locks the graduated full-range position) */
  locker: Address;
  /** `PonsV2BuybackVault` */
  buybackVault: Address;
  /** `GraduationExecutor` */
  graduationExecutor: Address;
  /** Uniswap v4 `PoolManager` of the graduated pools */
  poolManager: Address;
}

/** Pons V2 on Robinhood Chain mainnet (4663), EIP-55 checksummed (`docs/SPEC.md` §9.1). */
export const PONS: Readonly<PonsAddresses> = Object.freeze({
  factory: '0x7eD598BcEf8bd9Edd8C97A195C6d13f40801EC7e',
  router: '0xe33E9E479dF8802cb0866d5d05258bEc4cF62948',
  feeEscrow: '0xd3AFEB2a57f70eF218Aa82451c51B2fb0416Ac9e',
  memeHook: '0xE5e702641Ea86F4ae6cC3cDaeD2B886f976Be044',
  locker: '0x267444D099b10fB5Ed7c3Cc7B7c767AdcA574952',
  buybackVault: '0x42df2a798f82289E177311362e8f5ccC45c1219c',
  graduationExecutor: '0xC7819B64A1dAECD7eC19856d026cb14EfBd89046',
  poolManager: '0x8366a39CC670B4001A1121B8F6A443A643e40951',
} satisfies PonsAddresses);

/** Pons V2 deployments keyed by chain id (mainnet only; testnet / anvil use mocks and env overrides). */
export const PONS_ADDRESSES: Readonly<Record<number, Readonly<PonsAddresses>>> = Object.freeze({
  [ROBINHOOD_CHAIN_ID]: PONS,
});

/** The Pons V2 contracts on `chainId`, or `undefined` (Pons is only deployed on 4663). */
export function ponsAddressesFor(chainId: number): Readonly<PonsAddresses> | undefined {
  return PONS_ADDRESSES[chainId];
}

/** Where a deployment's minds trade: Pons V2 (§9) or the in-house bonding curve (§2). */
export type Venue = 'pons' | 'curve';

/** The default venue of a chain: Pons on mainnet (4663), the in-house curve elsewhere (§9). */
export function defaultVenue(chainId: number): Venue {
  return chainId === ROBINHOOD_CHAIN_ID ? 'pons' : 'curve';
}

/**
 * One deployment, as written to `contracts/deployments/<chainId>.json` by `script/Deploy.s.sol`
 * (`venue: 'curve'`: `launchpad`, `graduator`, `graduatorKind`) or `script/DeployPons.s.sol`
 * (`venue: 'pons'`: `registry`). Records written before §9 have no `venue` and are `curve`.
 */
export interface DeploymentRecord {
  chainId: number;
  venue: Venue;
  /** `MindLaunchpad` (curve deployments). */
  launchpad?: Address;
  /** Graduator wired into the launchpad (curve deployments). */
  graduator?: Address;
  graduatorKind?: 'uniswapv3' | 'mock';
  /** `PonsMindRegistry` (Pons deployments). */
  registry?: Address;
  /** Unix seconds (`block.timestamp` of the deployment). */
  deployedAt: number;
}

export { DEPLOYMENTS };

const ZERO = '0x0000000000000000000000000000000000000000';

const nonZero = (a: Address | undefined): Address | undefined => (a === undefined || a.toLowerCase() === ZERO ? undefined : a);

/**
 * The deployed `MindLaunchpad` for `chainId` from {@link DEPLOYMENTS}, or `undefined` (also when
 * the recorded address is the zero address or the deployment has no launchpad).
 */
export function launchpadAddress(chainId: number): Address | undefined {
  return nonZero(DEPLOYMENTS[chainId]?.launchpad);
}

/**
 * The deployed `PonsMindRegistry` for `chainId` from {@link DEPLOYMENTS}, or `undefined` (also when
 * the recorded address is the zero address or the deployment has no registry).
 */
export function registryAddress(chainId: number): Address | undefined {
  return nonZero(DEPLOYMENTS[chainId]?.registry);
}
