// AUTO-GENERATED by scripts/sync-deployments.mjs from contracts/deployments/*.json — do not edit.
// Regenerate with `pnpm deployments:sync` (node scripts/sync-deployments.mjs).
import type { DeploymentRecord } from './addresses.js';

/** Deployed contracts keyed by chain id. */
export const DEPLOYMENTS: Readonly<Record<number, DeploymentRecord>> = Object.freeze({});
